# Generated by Django 5.0.7 on 2024-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_customuser_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
