# Generated by Django 5.0.7 on 2024-07-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.BooleanField(blank=True, null=True)),
                ("email", models.EmailField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("day_join", models.DateField()),
            ],
        ),
    ]
