# Generated by Django 5.0.7 on 2024-07-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_userresume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserResume",
        ),
    ]
